name: rslaw
favicon: null
layout_spectrum: 0.031104327645152807
typography_spectrum: 0.3234582426957786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.057632078882306814
  lightness: 0.16232848749496043
  saturation: 0.4471451628487557
  rhythmicContrast: 0.31002790364436805
purpose: []
